#server:
#  port: 5000
#---
#environment: prod
#server:
#  port: 7070
#
#---
#environment: test
#server:
#  port: 4000
server:
  port: 5000
---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 7070
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 4000






